### ISSUE TITLE
如何读取证书信息？

### ISSUE THREAD

**Issue by mynewstart** [SewellDinG/scapy-ssl_tls-demo#1]
您好，直接使用您的上述程序无法解析出证书信息。貌似使用scapy_ssl_tls.ssl_tls包可以解析，但是如何利用这个包读取pcap文件呢？

**Comment by SewellDinG** [comment]
这个Demo没有涉及到证书信息提取，如果scapy支持，你直接参考它的帮助文档就能拿到，具体在tls_decode()，程序也很简单，相应位置也有注释。
